version: '2'
services:
    hipsterstore-app:
        image: hipsterstore
        external_links:
            - hipsterstore-mysql:mysql
            - hipsterstore-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hipsterstore?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    hipsterstore-mysql:
        extends:
            file: mysql.yml
            service: hipsterstore-mysql
    hipsterstore-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: hipsterstore-elasticsearch
